export const actionTypes = {
    INPUT:'INPUT',
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    CHECKBOX:'CHECKBOX',
    FETCHING_START:'FETCHING_START',
    FETCHING_SUCCESS:'FETCHING_SUCCESS',
    FETCHING_ERROR:'FETCHING_ERROR',
    ADDTOCART:'ADDTOCART'
}